### ISSUE TITLE
Hide badge feature 

### ISSUE THREAD

**Issue by femazolam** [enchanted-sword/dashboard-unfucker#190] opened 2023-12-15 04:59 UTC
it's been hiding my badge for a few days now. i tried toggling on and off the hide badge feature but nothing works. i'm on latest version i think v5.5.4

**Comment by enchanted-sword** [comment] 2023-12-15 14:52
What's your url? I've had one other person report a similar issue before but I haven't been able to replicate it in any capacity.

**Comment by punietis** [comment] 2023-12-16 06:22
I think I'm having the same issue! My blog has one badge (the lunar phase one), but it doesn't show up on my dash when I reblog stuff. I can see other people's badges, though:
<img width="385" alt="Screenshot 2023-12-15 at 10 21 21 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/5605350/85ceb1ac-936a-44dc-a23a-9beeff7bea0c">

My badge does show up when I turn off dashboard unfucker:
<img width="354" alt="Screenshot 2023-12-15 at 10 22 20 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/5605350/ee859e2e-80df-4f02-8b6c-5e89a07ccec1">

My URL is sunhitsthewater (it's a side blog, if that makes a difference). I'm on 5.5.5.

**Comment by enchanted-sword** [comment] 2023-12-16 19:47
It turns out it was caused by the header fixing feature and not the badge hiding feature, as for some reason the reblog parent's badge container element is outside of the container that holds the rest of the parent data. Should be fixed in the latest version.

**Closed by enchanted-sword** 2023-12-16 19:47 UTC
Labels: bug

**Comment by punietis** [comment] 2023-12-16 21:52
The fix worked! Thank you!
