### ISSUE TITLE
Revert messaging redesign no longer works

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#152] opened 2023-11-02 13:33 UTC
**Describe the bug**
The messaging redesign still appears now, even if you previously tried to disable it.

**To Reproduce**
1. Enable "disable messaging redesign"
2. Have a message

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/543a740f-6576-432c-9538-cda0190ccd03)

**Version (please complete the following information):**
 - Firefox 119.0
 - Version 5.2.1

**Additional context**
Genuinely have no idea how this happened. It worked just fine yesterday.

**Comment by enchanted-sword** [comment] 2023-11-02 16:49
Duplicate of #151

**Closed** 2023-11-02 16:49 UTC
Labels: bug, duplicate
