### ISSUE TITLE
Dashboard unfucker no longer works

### ISSUE THREAD

**Issue by octonusm9000** [enchanted-sword/dashboard-unfucker#193] opened 2023-12-20 05:01 UTC
I think tumblr finally put the finally nail in the coffin by blocking whatever request this script is trying to do. It won't co-operate AT ALL ;(( I hate tumblr I am so done

**Comment by citrusella** [comment] 2023-12-20 09:06
Is it just not modifying anything or something else? (If it's the former, is there a chance this is a duplicate of #188?)

**Comment by octonusm9000** [comment] 2023-12-20 15:20
i dont know ;( it's just not there you have to keep refreshing the page and
it loads if it feels like it, tumblr is fighting this those asshats

**Comment by AbelardTullus** [comment] 2023-12-31 15:37
Encountering this issue as well, it's just flat out not working for me. (Firefox 121.0)

**Comment by danareadsbooks** [comment] 2024-01-06 15:26
This is also happening with me on Firefox 120.0 and also when I updated Firefox to 121.0. 
On Chrome it works fine.

**Comment by TernaryC** [comment] 2024-01-10 22:44
Encountering a similar if not same issue on Firefox 119.0.1. 
Most of the time, on first page load Dashboard Unfucker will simply not load. Between 1-and-5 refreshes are required to get it to load up, after which point it will work continuously until that tab leaves tumblr.com/dashboard.
Based on minor experimenting, it seems like waiting for the page to load fully before refreshing can reduce the number of attempts it takes, but I'm not positive about that. It feels mostly random.

**Comment by xlados** [comment] 2024-01-29 20:35
experiencing a similar (or same?) issue, tested on firefox 122.0 on 2 separate computers, one running endeavourOS and the other running arch linux. either refuses to load or does so extremely slowly, seems to hang on transferring data. 

i did in fact test on both that it was only happening with dashboard unfucker enabled. this only started happening to me a few days ago and before that it was working flawlessly. unfortunately i'm not entirely sure what exactly could've changed to cause it as it just stopped loading properly while i was trying to reblog something

**Comment by citrusella** [comment] 2024-02-05 04:19
Yeah, I noticed a *severe* uptick right around when they turned off Tumblr Live. Dunno that that change is related, but...

**Comment by anoraktrend** [comment] 2024-02-12 08:20
issue is possibly due to the user-js provider. On firefox, I use tampermonkey for my userjs. I've had issues with grease monkey with this script so I try not to use it.

**Comment by citrusella** [comment] 2024-02-12 09:14
This is happening in Tampermonkey. (At least if this and what's described in #188 are the same or similar issue--this issue doesn't have as much context as the other one.)

**Comment by danareadsbooks** [comment] 2024-02-15 14:44
I am also using tampermonkey. I tried using violentmonkey as well, but it is the same issue. 
Still working on Chrome while using tampermonkey, but not on firefox.

**Comment by cursdgmr** [comment] 2024-03-23 01:29
Using tampermonkey on chrome and firefox, can confirm that it is no longer working on either. I'm aware it isn't being maintained anymore but just thought it would be good to document for anyone coming here for help.

**Comment by imnotsuspiciousshh** [comment] 2024-04-10 16:26
Using Tampermonkey on Firefox and it just went down for me. I am also aware this isn't being maintained anymore but I want to let people know who might be having similar issues this is still happening

**Closed** 2024-04-10 16:45 UTC
Labels: bug, can't reproduce
