### ISSUE TITLE
Can't get to dashboard view of blog

### ISSUE THREAD

**Issue by BBkat13** [enchanted-sword/dashboard-unfucker#203] opened 2023-12-21 16:50 UTC
When I click on any floating icon, including my own, on the dashboard it open a new tab to view the blog in, instead of the dashboard view of the blog. 
It was doing this up until yesterday when I had to update tampermonkey (which I had to do on account of all the icons just straight up vanishing from the dashboard).

What it should be doing-
<img width="1077" alt="Screen Shot 2023-12-21 at 11 44 49 AM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/114542020/f91ece74-68ea-4e07-8415-4b8560f989f8">
opening in the 'dashboard' view of the blog'

What it is actually doing-
<img width="280" alt="Screen Shot 2023-12-21 at 11 45 15 AM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/114542020/e791034c-c9b7-49ac-a1d1-632eb5e8ba0e">
Literally opening a whole new tab.

The problem is, while I can easily bring up the dashboard view by clicking on the blog name, this doesn't help me in bringing up MY OWN blog as, I only have my floating icon to click.

**Comment by enchanted-sword** [comment] 2023-12-21 17:18
Fixed in v5.6.1

**Comment by BBkat13** [comment] 2023-12-21 17:27
Well, now it's just doing both at once. When I click my icon it's opening up the dashboard view AND a new tab(at least for clicking my icon, clicking someone else's just gives the dashview). And also giving me these, half a floating icon in the dashboard view.

<img width="673" alt="Screen Shot 2023-12-21 at 12 24 57 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/114542020/978ba054-fe35-421e-8a94-390df5acbbd4">

**Comment by enchanted-sword** [comment] 2023-12-21 17:54
I think the default tumblr function for navigating to the blog view itself is broken, I'll add a custom function for it.

**Comment by BBkat13** [comment] 2023-12-21 17:58
I should note, the screwy floating icons in dashboard view are happening regardless on the blog I am viewing, mine or someone else's.

**Comment by enchanted-sword** [comment] 2023-12-21 21:17
> Well, now it's just doing both at once
That was the previous behaviour, although it should've prevent the new tab from opening since it's technically a popup by design.

This is definitely an external issue as it persists with the script disabled; the links in general also seem incredibly buggy right now, and the behaviour isn't consistent for me across accounts, browsers, or even which links I click.

**Closed by enchanted-sword** 2023-12-21 21:17 UTC
Labels: bug, tumblr-side bug

**Comment by BBkat13** [comment] 2023-12-21 21:47
> > Well, now it's just doing both at once
> > That was the previous behaviour, although it should've prevent the new tab from opening since it's technically a popup by design.
> 
> This is definitely an external issue as it persists with the script disabled; the links in general also seem incredibly buggy right now, and the behaviour isn't consistent for me across accounts, browsers, or even which links I click.

It's, not an external issue though??? When I disable the script and get the regular dashboard back the in-dash views that open are fine. No glitchy floating icons and clicking my own posts only opens up the dashboard view of my blog. 
But turning the script back on gets me the above issues (the fragments of floating icons and my blog being opened up in dashboard view and blog view in a new tab.

I'm using the most recent version of Firefox (literally just updated it) if that helps.

**Comment by enchanted-sword** [comment] 2023-12-21 23:24
It depends on where you click; the post header will open it in blog view, whereas the icon will open it in theme view. That holds true for me across all of my testing accounts with the script both disabled and enabled in the latest version of Firefox (v123). The icons only navigate to blog view (while still opening theme view in a new tab) for me in my Firefox Developer profile (v122), but I don't think the version is what causes it since the changelogs don't mention anything related to event propagation.

The fragmented icons in blog view is also fixed in the latest version, but depending on auto-update settings you might have to manually update it to fix it.

**Comment by BBkat13** [comment] 2023-12-22 00:01
But, it IS all up to date. My Firefox literally just updated to ver 121 (which is says is up to date and the latest version, even on their website), and my Tampermonkey AND the unfucker script are all up to date (unless there's an update coming but not yet out). And it's doing the fragmented icons.
