### ISSUE TITLE
"Reblogged from" header sometimes displays the wrong blog name, or the name is displayed twice

### ISSUE THREAD

**Issue by whiteangel123** [enchanted-sword/dashboard-unfucker#94] opened 2023-08-27 11:47 UTC
**Describe the bug**
In Dashboard, the "[blog] reblogged from [second blog]" header displays the [second blog]'s name twice. When going to individual posts (by clicking on post's header), the [second blog]'s name is sometimes displayed incorectly.

**To Reproduce**
1. It already looks like that in my Dashboard.
2. Click on post header to go to the individual post from Dashboard.

**Screenshots**

How a post looks like on Dashboard:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/36785520/b5f43dd0-309c-4006-8c1d-40b78954db17)

How Individual post looks like with script turned on (incorrect [reblogged from] blog name):

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/36785520/910185c9-b908-4e19-b258-4499a8af32e0)

How post looks like without the script (correct "reblogged from" blog):

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/36785520/c67e3c7f-c5e7-444a-8feb-7fe8f8567af2)

**Version (please complete the following information):**
 - Browser and version: Chrome Version 116.0.5845.111
 - Version 3.6.6a

**Comment by enchanted-sword** [comment] 2023-08-27 14:24
Can't reproduce the "double" effect; my best guess is maybe a virtual scroller bug where it processes the posts twice. When I overhaul the header/icon methods I'll add a specific attribute to processed posts to prevent them from being reprocessed again. as for the incorrect name, the tumblr-side bug (or feature? who knows at this point) where it doesn't show who you reblogged a post from is also present when you reblog a post from whoever made the last addition to a post. This will also be fixed in the overhaul as I'm switching to parsing the raw NPF data to find the reblog parent.

**Comment by whiteangel123** [comment] 2023-08-27 17:27
Just opened Tumblr again and the double name is gone. I guess it's just a momentary glitch.

**Closed** 2023-09-01 14:20 UTC
Labels: bug, can't reproduce
