### ISSUE TITLE
dashboard unfucker bug with search/ask

### ISSUE THREAD

**Issue by Ferinehuntress** [enchanted-sword/dashboard-unfucker#131] opened 2023-09-18 20:30 UTC
When going to the dashboard accounts, trying to use things like the search function or the ask button won't work. I've pressed it multiple times and it will not pop up or let me use it.

**Comment by enchanted-sword** [comment] 2023-09-18 20:40
What version of the script are you using?

**Comment by Kennylotl** [comment] 2023-09-18 21:04
Funnily enough, I actually came here to report the same bug. You can still use the tab key to navigate through those buttons and enter to click them, but it's fixed in the latest version anyway. (At least for me, I guess it's possible it isn't for others)

**Comment by arcanescion** [comment] 2023-09-18 21:34
My version is v4.4.3.

and ohh, okay, I'll use teh tab function til I can get this fixed.

**Comment by arcanescion** [comment] 2023-09-18 21:35
okay, I just updated to v4.4.4 and its still the same.

**Closed as completed** 2023-09-19 01:52 UTC
Labels: bug

**Comment by RocketDrifter** [comment] 2023-09-19 01:58
I was in the middle of commenting that this issue was affecting me as well, when suddenly you'd fixed it. Thanks for that!
You mentioned you don't know why the first fix worked for some users but not others, so if it helps, I'm using Firefox with the Xkit Rewritten extension installed. That should be the only other thing that could be affecting it, if the issue isn't Firefox or Tumblr itself.

**Comment by arcanescion** [comment] 2023-09-19 03:02
Thank you so much!! I'll let my friends know to update yours cause its fixed for me too! Appreciate it so muhc!!
