### ISSUE TITLE
Is it me or unfucker

### ISSUE THREAD

**Issue by BloodyMonthly** [enchanted-sword/dashboard-unfucker#155] opened 2023-11-03 01:13 UTC
I switched from Stylus to Dashboard Unfucker when Stylus stopped working (consistently at least) in fixing the tumblr dash, but recently Unfucker has been reloading new tabs of tumblr and refreshing the page before I even begin to scroll through and actually catch up to where I last left off. This wasn't an issue when I first switched to Unfucker, even when I had neglected to remove Stylus, but I still have Xkit running as well as other extensions (uBlock Origin, ClearURLS, AdBlocker Ultimate, minerBlock, Privacy Possum), so I'm not sure if this is an error with one of the recent updates or just clutter on my end.

I don't need to go far to reproduce for it's immediate on loading, but so far as Unfucker settings I have:
General Configuration
- hide dashboard tabs
- hide recommended blogs
- hide tumblr radar
- hide tumblr shop
- hide badges
- highlight likely bots in the activity feed
- show who follows you in the activity feed
Advanced Configuration (does 'requires a page reload' mean 'reloads a new tab'?)
- disable tumblr live
- disable tumblr domains
- revert activity feed redesign
- revert searchbar update
- enable adding polls to reblogs
- disable "post without tags" nag
- re-add unread post notifications to the corner of the home icon
- display full note counts
- display exact vote counts on poll answers
- show hidden NSFW posts in the timeline

I'm on Firefox 119.0 (64-bit) and Dashboard Unfucker v5.2.2

**Comment by enchanted-sword** [comment] 2023-11-03 09:28
Duplicate of #146.

**Closed by enchanted-sword** 2023-11-03 09:28 UTC
Labels: bug, duplicate
